# Login once
# Subscribe NIFTY option tokens
# Receive live LTP update
# Print live CE/PE values
from neo_api_client import NeoAPI
from dotenv import load_dotenv
import os
import time
from datetime import datetime

load_dotenv()

consumer_key = os.getenv("CONSUMER_KEY")
mobile = os.getenv("MOBILE_NUMBER")
ucc = os.getenv("UCC")
mpin = os.getenv("MPIN")

client = NeoAPI(
    consumer_key=consumer_key,
    environment="prod"
)

totp = input("Enter TOTP from authenticator app: ")

response = client.totp_login(
    mobile_number="+91" + str(mobile),
    ucc=ucc,
    totp=totp
)

print("Login response:", response)

validate_response = client.totp_validate(
    mpin=mpin
)

print("2FA response:", validate_response)
print("LOGIN SUCCESSFUL")
with open("live_ltp.csv", "w") as f:
    f.write("Time,Symbol,Token,LTP,VOL,OI\n")

# Read latest ATM tokens generated by main.py

with open("tokens.txt", "r") as f:
    token_lines = [line.strip() for line in f if line.strip()]

# tokens = [
#     {"instrument_token": t}
#     for t in token_lines
# ]

def on_message(message):
    try:
        data = message.get("data", [])

        for tick in data:
            token = str(tick.get("tk", "")).strip()

            ltp = (
                tick.get("ltp")
                or tick.get("last_price")
                or tick.get("last_traded_price")
                or 0
            )

            if token == "26000" and ltp:
                with open("nifty_spot_live.txt", "w") as f:
                    f.write(str(ltp))

                print(f"NIFTY SPOT = {ltp}")
                return

    except Exception as e:
        print("SPOT PARSE ERROR:", e)

            
def on_error(error):
    print("ERROR:", error)

def on_close(message):
    print("CLOSED:", message)
    print("Websocket closed. Run python live_feed.py again if needed.")

def on_open(message):
    print("WEBSOCKET OPENED:", message)

client.on_message = on_message
client.on_error = on_error
client.on_close = on_close
client.on_open = on_open

# with open("tokens.txt", "r") as f:
#     token_lines = [line.strip() for line in f if line.strip()]

tokens = [
    {
        "instrument_token": "26000",
        "exchange_segment": "nse_cm"
    }
]

# tokens += [
#     {
#         "instrument_token": t,
#         "exchange_segment": "nse_fo"
#     }
#     for t in token_lines
# ]

print("Total Tokens =", len(tokens))

client.subscribe(
    instrument_tokens=[{
        "instrument_token": "26000",
        "exchange_segment": "nse_cm"
    }],
    isIndex=True,
    isDepth=False,
)

# client.subscribe(
#     instrument_tokens=[
#         {
#             "instrument_token": t,
#             "exchange_segment": "nse_fo"
#         }
#         for t in token_lines
#     ],
#     isIndex=False,
#     isDepth=False,
# )
print("Subscribed. Waiting for NIFTY spot ticks...")

while True:
    time.sleep(1)