# Login once
# Subscribe NIFTY option tokens
# Receive live LTP update
# Print live CE/PE values
from neo_api_client import NeoAPI
from dotenv import load_dotenv
import os
import time
from datetime import datetime

load_dotenv()

consumer_key = os.getenv("CONSUMER_KEY")
mobile = os.getenv("MOBILE_NUMBER")
ucc = os.getenv("UCC")
mpin = os.getenv("MPIN")

client = NeoAPI(
    consumer_key=consumer_key,
    environment="prod"
)

totp = input("Enter TOTP from authenticator app: ")

response = client.totp_login(
    mobile_number="+91" + str(mobile),
    ucc=ucc,
    totp=totp
)

print("Login response:", response)

validate_response = client.totp_validate(
    mpin=mpin
)

print("2FA response:", validate_response)
print("LOGIN SUCCESSFUL")
with open("live_ltp.csv", "w") as f:
    f.write("Time,Symbol,Token,LTP,VOL,OI\n")

# Read latest ATM tokens generated by main.py

with open("tokens.txt", "r") as f:
    token_lines = [line.strip() for line in f if line.strip()]

tokens = [
    {"instrument_token": t}
    for t in token_lines
]

def on_message(message):
    try:
        data = message.get("data", [])

        for tick in data:
                print("RAW TICK =", tick)
                token = str(tick.get("tk")).strip()

                ltp = (
                    tick.get("ltp")
                    or tick.get("last_price")
                    or tick.get("last_traded_price")
                    or 0
                )

                volume = (
                    tick.get("v")
                    or tick.get("vol")
                    or tick.get("volume")
                    or tick.get("Volume")
                    
                    or 0
                )
                oi = (
                    tick.get("oi")
                    or tick.get("open_int")
                    or tick.get("openInterest")
                    or 0
                )

                symbol = str(tick.get("ts", ""))
                if not symbol:
                    symbol = str(tick.get("tk", ""))

                
                # print("MATCHED SYMBOL =", symbol, "TOKEN =", token)

                with open("live_ltp.csv", "a") as f:

                    f.write(
                        f"{datetime.now().strftime('%H:%M:%S')},"
                        f"{symbol},{token},{ltp},{volume},{oi}\n"
                    )

        import pandas as pd
        df_check = pd.read_csv("live_ltp.csv")
        print("Rows =", len(df_check))
        print(f"{symbol} | TOKEN={token} | LTP={ltp} | VOL={volume} | OI={oi}")
        try:
                df = pd.read_csv("option_chain.csv")

                if "CE Token" in df.columns:
                    df.loc[df["CE Token"].astype(str) == str(token), "CE_LTP"] = ltp

                    df.loc[df["CE Token"].astype(str) == str(token), "CE OI"] = oi

                if "PE Token" in df.columns:
                    df.loc[df["PE Token"].astype(str) == str(token), "PE_LTP"] = ltp

                    df.loc[df["PE Token"].astype(str) == str(token), "PE OI"] = oi

                df.to_csv("option_chain.csv", index=False)

        except Exception as e:
                print("CSV update error:", e)
    except Exception as e:
        print("LIVE DATA:", message)
        print("PARSE ERROR:", e)

        def on_error(error):
                print("ERROR:", error)

    
def on_error(error):
    print("ERROR:", error)

def on_close(message):
    print("CLOSED:", message)
    print("Websocket closed. Run python live_feed.py again if needed.")

def on_open(message):
    print("WEBSOCKET OPENED:", message)

client.on_message = on_message
client.on_error = on_error
client.on_close = on_close
client.on_open = on_open

with open("tokens.txt", "r") as f:
    token_lines = [line.strip() for line in f if line.strip()]

tokens = [
    {
        "instrument_token": t,
        "exchange_segment": "nse_fo"
    }
    for t in token_lines
]

print("Total Tokens =", len(tokens))

client.subscribe(
    instrument_tokens=tokens,
    isIndex=False,
    isDepth=False,
)

print("Subscribed. Waiting for live ticks...")

while True:
    time.sleep(1)